env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:import/typescript'
  - 'airbnb'
  - 'airbnb-typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'react/jsx-filename-extension': [1, {'extensions': ['.tsx', '.ts']}],
    'no-use-before-define': 'off',
    '@typescript-eslint/no-use-before-define': ['error'],
    '@typescript-eslint/no-unused-vars': ['warn'],
  }
